### PR TITLE
Fix Cover Theme backgrounds

### LINKED ISSUE #62: Cover Themes black bars
Theres a big black bar in "My Profile"

image

also playlist headers are black:

image

### PR DESCRIPTION
**Pull request by n1ckoates**
* Made `tabListWrapper`'s background transparent.
* Added a new gradient overlay to playlist/album headers which uses theme colors, overriding Tidal's built-in one that's a black overlay.

Closes #62

### CODE REVIEW

File: plugins/CoverTheme/src/index.ts [hunk 1]
```diff
@@ -53,7 +53,7 @@ const unloadIntercept = intercept("playbackControls/TIME_UPDATE", ([time]) => {
 export function updateCSS() {
 	if (settings.transparentTheme) {
 		const styles = `
-		#wimp, main, .sidebarWrapper, [class^="mainContainer"] {
+		#wimp, main, .sidebarWrapper, [class^="mainContainer"], [class^="tabListWrapper"] {
```
Comment (Araxeus) [inline plugins/CoverTheme/src/index.ts:56]: I dont think that the tablist should have no background at all - it is fixed position, aka scrolls with the document

image
